export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Not_FoundLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<section>

  {children}
</section>
 
  )
}
