import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Head from "next/head";
import Footer from "@/components/Footer/Footer";
import Provider from "./Provider";
import { Locale } from "@/i18n-config";
import { getDictionary } from "@/get-dictionary";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,params:{lang}
}: Readonly<{
  children: React.ReactNode;
  params:{lang:Locale}
}>) {
 const dictionary= (await getDictionary(lang)).LayoutLanguage;
  return (
    <html lang={lang}>
     <Head>
     <meta name="google-site-verification" content="Jhn1fxL5T9d68sryBVg3rsqdIHBChNEbCb6532yeRpE" />
     <link
  rel="stylesheet"
  type="text/css"
  charSet="UTF-8"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
/>

     </Head>
      <body id="wrapper" className={inter.className} suppressHydrationWarning={true}>
<Provider>
        <Header Locale={lang} dictionary={dictionary.header}/>
        {children}   
<Footer dictionary={dictionary.footer} lang={lang}/>
   </Provider>

        </body>
    </html>
  );
}
